Async with multiple threads
Midgrad/Jerom-The-Mavlink pull request #14
Opened 2021-10-21 09:11 UTC by nnhw

Attempt to build working data exchange with multiple threads

2021-10-22 09:17 UTC, MishkaRogachev requested changes
Some CS questions

2021-10-22 09:17 UTC, MishkaRogachev commented on impl/include/link_transceiver.h
> +    void receivedData(const QByteArray& data);
Сonst refs are dangerous in signals - `void receivedData(QByteArray data);`

2021-10-22 09:17 UTC, MishkaRogachev commented on impl/include/mavlink_transceiver.h
> +signals:
signals before private slots

2021-10-22 09:17 UTC, MishkaRogachev commented on impl/include/link_transceiver.h
> +    data_source::LinkPtr const m_link;
empty line between methods and members

2021-10-22 09:17 UTC, MishkaRogachev commented on impl/include/mavlink_transceiver.h
> +    void parseMessage(const QByteArray& data);
empty line between methods and members

2021-10-22 09:17 UTC, MishkaRogachev commented on impl/include/mavlink_transceiver.h
> +    QVector<data_source::LinkTransceiverThreaded*> m_linkTransceiverThreaded;
Can we use here interface class?
`QVector<data_source::ILinkTransceiver> m_linkTransceivers`

2021-10-22 09:40 UTC, nnhw commented on impl/include/mavlink_transceiver.h
> +    QVector<data_source::LinkTransceiverThreaded*> m_linkTransceiverThreaded;
yes, done

2021-10-22 09:40 UTC, nnhw commented on impl/include/link_transceiver.h
> +    void receivedData(const QByteArray& data);
changed for by value passing

2021-10-25 17:56 UTC, MishkaRogachev approved these changes

2021-10-25 17:56 UTC, merged