Links refactor
Midgrad/Jerom-The-Mavlink pull request #16
Opened 2022-01-18 14:33 UTC by nnhw

2022-01-18 16:49 UTC, MishkaRogachev requested changes
Some minor issues

2022-01-18 16:49 UTC, MishkaRogachev commented on src/module/meta.json
> +  "description": "Mavlink communication protocol module",
Jerom-The-Mavlink is not only protocol module, it contatins lots of non-protocol stuff

2022-01-18 16:49 UTC, MishkaRogachev commented on src/module/meta.json
> +    "Vegur"
This can be deleted

2022-01-18 16:49 UTC, MishkaRogachev commented on src/module/module_jerom_the_mavlink.cpp
> +    m_protocol = new data_source::MavlinkProtocolThreaded(new data_source::MavlinkProtocol(&factory,
If creation in init(), destruction must be in done(), or use shared/scoped pointer

2022-01-18 16:49 UTC, MishkaRogachev commented on src/protocols/mavlink_protocol.cpp
> +    for (domain::IMavlinkHandler* handler : qAsConst(m_handlers))
qDeleteAll()

2022-01-18 16:49 UTC, MishkaRogachev commented on src/protocols/mavlink_protocol.h
> +#include <memory>
unneeded

2022-01-18 16:49 UTC, MishkaRogachev commented on src/protocols/mavlink_protocol.h
> +    domain::MavlinkHandlerContext m_context;
new line

2022-01-18 16:49 UTC, MishkaRogachev commented on src/protocols/mavlink_protocol_threaded.cpp
> +    emit resendData(data);
dataRecived?

2022-01-20 09:55 UTC, MishkaRogachev requested changes

2022-01-20 09:55 UTC, MishkaRogachev commented on src/module/module_jerom_the_mavlink.cpp
> +    delete m_protocol;
MavlinkProtocolThreaded is QObject, we can just set parent for  m_protocol

2022-01-20 12:29 UTC, nnhw commented on src/module/module_jerom_the_mavlink.cpp
> +    delete m_protocol;
ok, MavlinkProtocolThreaded is already a QObject child for this module-object

2022-01-21 08:57 UTC, MishkaRogachev approved these changes

2022-01-21 08:58 UTC, merged